### ISSUE TITLE
Use USB Remote who is already Paired by CC41 Control Unit

### ISSUE THREAD

**Issue by dunimaniac** [RainerStaude/hass-becker-component-plus-pybecker#29]
Hello Rainer,

is it possible to use an already paired Centronic Stick with this integration?

Cheers

**Comment by RainerStaude** [comment]
To be honest I don't know.
The stick will work. But I'm not sure if you will need to pair your shutters again with this integration.
To my knowledge the stick does not store anything. Any data is stored either in the CC41 or within Home Assistant. So why not give it a try?
You should be able to switch between CC41 and Home Assistant without any impact. You just might to pres the Stop button for each unit several times after changing between CC41 and Home Assistant in order to sync with the shutters.

**Comment by dunimaniac** [comment]
Hey Rainer, i managed to pair 9 Covers flawlessly and bridge them to Homekit. Thank you for your integration! I use the Traveltimes to controll the covers and the next step is to add the existing walltransmitter to track the positions :)

**Comment by dunimaniac** [comment]
Hey Rainer, i managed to pair 9 Covers flawlessly and bridge them to Homekit. Thank you for your integration! I use the Traveltimes to controll the covers and the next step is to add the existing walltransmitter to track the positions :)
